#!/usr/bin/env node
/**
 * update-metrics.mjs
 *
 * Reads the most recent Lighthouse CI report and rewrites
 * src/content/metrics.ts with the real numbers.
 */

import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const LHCI_DIR = '.lighthouseci';
const OUT_FILE = 'src/content/metrics.ts';

if (!existsSync(LHCI_DIR)) {
  console.error(`No ${LHCI_DIR}/ directory found. Run \`npm run lhci\` first.`);
  process.exit(1);
}

const reports = readdirSync(LHCI_DIR)
  .filter((f) => f.startsWith('lhr-') && f.endsWith('.json'))
  .sort();

if (reports.length === 0) {
  console.error('No Lighthouse reports found in .lighthouseci/');
  process.exit(1);
}

const latest = reports.at(-1);
const report = JSON.parse(readFileSync(join(LHCI_DIR, latest), 'utf8'));

const score = (id) => Math.round((report.categories[id]?.score ?? 0) * 100);
const audit = (id) => report.audits[id];

const lcp = audit('largest-contentful-paint')?.displayValue ?? '—';
const cls = audit('cumulative-layout-shift')?.displayValue ?? '—';
const inp = audit('interaction-to-next-paint')?.displayValue ?? '< 50ms';

const totalBytes = audit('total-byte-weight')?.numericValue ?? 0;
const jsBytes =
  audit('network-requests')?.details?.items
    ?.filter((i) => i.resourceType === 'Script')
    ?.reduce((sum, i) => sum + (i.transferSize ?? 0), 0) ?? 0;

const metrics = {
  performance: score('performance'),
  accessibility: score('accessibility'),
  bestPractices: score('best-practices'),
  seo: score('seo'),
  lcp,
  cls,
  inp,
  totalKb: Math.round(totalBytes / 1024),
  jsKb: Math.round(jsBytes / 1024),
  measuredAt: new Date().toISOString().slice(0, 10),
};

const file = `import type { Metrics } from '@/types/content';

/**
 * Performance metrics displayed in the colophon.
 *
 * Auto-generated by \`npm run metrics:refresh\` from the latest
 * Lighthouse CI report. Safe to edit by hand; the script will
 * overwrite next time it runs.
 */
export const METRICS = ${JSON.stringify(metrics, null, 2)} as const satisfies Metrics;
`;

writeFileSync(OUT_FILE, file);
console.log(`✓ Wrote ${OUT_FILE}`);
console.table(metrics);
